name: Build
permissions:
  contents: read # Default top-level permission

on:
  workflow_dispatch:
#  push:

jobs:
  build-apple:
    runs-on: macos-latest
    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to publish to GitHub Packages

    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set dynamic version
        run: |
          ls -l
          sed -i '' 's/version = "[^"]*"/version = "1.6.${{ github.run_number }}"/' build.gradle.kts

      - name: Create local.properties
        run: |
          echo "githubActor=${{ github.actor }}" > local.properties
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> local.properties
          echo "signingInMemoryKeyId=${{ secrets.SIGNINGINMEMORYKEYID }}" >> local.properties
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNINGINMEMORYKEYPASSWORD }}" >> local.properties
          echo "signingInMemoryKey=${{ secrets.SIGNINGINMEMORYKEY }}" >> local.properties


      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.konan
          key: general-lib-cache-apple

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            sqlx4k-mysql/src/rust
            sqlx4k-postgres/src/rust
            sqlx4k-sqlite/src/rust
          cache-all-crates: 'true'
          cache-bin: 'true'
          key: rust-lib-cache-apple

      - name: Setup Rust & cargo
        run: |
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Gradle Build
        run: |
          ./gradlew \
          publishIosArm64PublicationToGithubRepository \
          publishIosSimulatorArm64PublicationToGithubRepository \
          publishMacosArm64PublicationToGithubRepository \
          publishMacosX64PublicationToGithubRepository \
          -Ptargets=apple

  build-non-apple:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set dynamic version
        run: |
          ls -l
          sed -i 's/version = "[^"]*"/version = "1.6.${{ github.run_number }}"/' build.gradle.kts

      - name: Create local.properties
        run: |
          echo "githubActor=${{ github.actor }}" > local.properties
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> local.properties
          echo "signingInMemoryKeyId=${{ secrets.SIGNINGINMEMORYKEYID }}" >> local.properties
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNINGINMEMORYKEYPASSWORD }}" >> local.properties
          echo "signingInMemoryKey=${{ secrets.SIGNINGINMEMORYKEY }}" >> local.properties

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.konan
          key: general-lib-cache

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            sqlx4k-mysql/src/rust
            sqlx4k-postgres/src/rust
            sqlx4k-sqlite/src/rust
          cache-all-crates: 'true'
          cache-bin: 'true'
          key: rust-lib-cache

      - name: Setup Rust & cargo
        run: |
          rustup target add x86_64-linux-android
          rustup target add aarch64-linux-android
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-pc-windows-gnu

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27  # Using a stable NDK version
          local-cache: true

      - name: Install cargo-ndk (with cache)
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-ndk

      - name: Install Toolchains
        run: |
          sudo apt update
          sudo apt install \
          build-essential \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          mingw-w64


      - name: Gradle Build
        run: |
          ./gradlew \
          publishAllPublicationsToGithubRepository \
          -Ptargets=non-apple